// ingest/audits/_util.ts
//
// Shared helpers for the Gate 0 (Elevation v1) one-off audit scans. Each scan
// reads published content, flags trust-critical defects, and emits BOTH a
// stdout table and a Markdown file for Jim to review. Nothing here auto-deletes
// or auto-edits published rows: the human-judgment scans produce a table and
// stop (per GATE_0_stop_the_bleeding.md).
//
// Run convention (mirrors package.json's extract:sample):
//   node --env-file=.env.local --import tsx ingest/audits/<scan>.ts
// so getDb() sees NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SECRET_KEY locally.

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const AUDIT_DIR = dirname(fileURLToPath(import.meta.url));

/** Was this module executed directly (not imported)? Mirrors ingest/run.ts. */
export function isMain(importMetaUrl: string): boolean {
  return importMetaUrl === `file://${process.argv[1]}`;
}

/** A single flagged cell in a review table. */
export interface Flag {
  id: string;
  title: string;
  table: string;
  column: string;
  snippet: string;
  note?: string;
}

/** Truncate + single-line a value so it fits a review cell. */
export function snippet(value: string, max = 160): string {
  const oneLine = value.replace(/\s+/g, ' ').trim();
  return oneLine.length > max ? `${oneLine.slice(0, max - 1)}…` : oneLine;
}

/** Escape a value for a Markdown table cell (pipes + newlines). */
function mdCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

/** Render flags as a GitHub-flavored Markdown table. */
export function toMarkdownTable(flags: Flag[]): string {
  if (!flags.length) return '_No rows flagged._\n';
  const header = '| # | id | title | table.column | snippet | note |\n|---|----|-------|--------------|---------|------|\n';
  const rows = flags
    .map((f, i) =>
      `| ${i + 1} | \`${f.id}\` | ${mdCell(f.title)} | \`${f.table}.${f.column}\` | ${mdCell(f.snippet)} | ${mdCell(f.note ?? '')} |`,
    )
    .join('\n');
  return header + rows + '\n';
}

/** Render a compact stdout table (title + column + snippet per line). */
export function printTable(flags: Flag[]): void {
  if (!flags.length) {
    console.log('  (clean: 0 rows flagged)');
    return;
  }
  for (const [i, f] of flags.entries()) {
    console.log(`  ${String(i + 1).padStart(3)}. [${f.table}.${f.column}] ${f.title}`);
    console.log(`       ${f.snippet}${f.note ? `  (${f.note})` : ''}`);
  }
}

/** Write a scan's Markdown report next to the script and echo the path. */
export function writeReport(basename: string, title: string, flags: Flag[]): string {
  const path = join(AUDIT_DIR, `${basename}.out.md`);
  const body =
    `# ${title}\n\n` +
    `Generated by \`ingest/audits/${basename}.ts\`. ${flags.length} row(s) flagged.\n\n` +
    toMarkdownTable(flags);
  writeFileSync(path, body, 'utf8');
  return path;
}
