// ingest/audits/emdash_purge.ts  (Gate 0 . G0.9 . THE GOLDEN RULE, layer 1)
//
// One-time DB-content purge of the em dash (U+2014). Scans every text column
// across the content tables, shows a review table with the proposed replacement,
// and (only with APPLY=1, after Jim spot-checks) rewrites each value with the
// shared normalizer. The transform is safe + mechanical, so auto-fix is allowed
// here; Jim reviews the diff first.
//
// Run (report):  node --env-file=.env.local --import tsx ingest/audits/emdash_purge.ts
// Run (apply):   APPLY=1 node --env-file=.env.local --import tsx ingest/audits/emdash_purge.ts

import { getDb } from '../db';
import { hasEmDash, stripEmDash } from '../../lib/text/stripEmDash';
import { AUDIT_DIR, isMain } from './_util';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

// (table, id column, text columns) tuples. A column that does not exist on this
// DB is skipped gracefully, so this list can name Gate-1 columns safely.
const TARGETS: { table: string; cols: string[] }[] = [
  { table: 'things', cols: ['title', 'blurb', 'blurb_long', 'reason_to_go', 'local_note', 'practical_note'] },
  { table: 'guides', cols: ['title', 'kicker', 'intro', 'now_note'] },
  { table: 'guide_stops', cols: ['label', 'note', 'sub'] },
  { table: 'recurring_schedules', cols: ['label'] },
  { table: 'editions', cols: ['subject', 'preheader', 'intro'] },
  { table: 'submissions', cols: ['submitter_name'] },
];

export interface PurgeFlag {
  table: string; id: string; column: string; before: string; after: string;
}

async function scanColumn(table: string, column: string): Promise<PurgeFlag[]> {
  const sb = getDb();
  const { data, error } = await sb.from(table).select(`id, ${column}`);
  if (error) {
    // Missing column / table -> skip quietly (e.g. Gate-1 practical_note not applied yet).
    if (/column .* does not exist|does not exist|Could not find/i.test(error.message)) return [];
    throw new Error(`${table}.${column}: ${error.message}`);
  }
  const flags: PurgeFlag[] = [];
  const rows = (data ?? []) as unknown as Array<Record<string, unknown>>;
  for (const row of rows) {
    const value = row[column];
    if (typeof value === 'string' && hasEmDash(value)) {
      flags.push({ table, id: row.id as string, column, before: value, after: stripEmDash(value) });
    }
  }
  return flags;
}

export async function runEmdashPurgeScan(): Promise<PurgeFlag[]> {
  const flags: PurgeFlag[] = [];
  for (const { table, cols } of TARGETS) {
    for (const col of cols) flags.push(...(await scanColumn(table, col)));
  }
  return flags;
}

async function applyPurge(flags: PurgeFlag[]): Promise<number> {
  const sb = getDb();
  let n = 0;
  for (const f of flags) {
    const { error } = await sb.from(f.table).update({ [f.column]: f.after }).eq('id', f.id);
    if (error) throw new Error(`update ${f.table}.${f.column} ${f.id}: ${error.message}`);
    n++;
  }
  return n;
}

function renderReport(flags: PurgeFlag[]): string {
  let md = `# G0.9 layer 1 . DB content em-dash purge\n\n` +
    `Generated by \`ingest/audits/emdash_purge.ts\`. ${flags.length} value(s) contain an em dash. ` +
    `Run with \`APPLY=1\` to rewrite them with the shared normalizer.\n\n`;
  if (!flags.length) return md + '_Clean: no em dashes in DB content._\n';
  md += `| table.column | id | before | after |\n|---|---|---|---|\n`;
  for (const f of flags) {
    const esc = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ').slice(0, 120);
    md += `| \`${f.table}.${f.column}\` | \`${f.id}\` | ${esc(f.before)} | ${esc(f.after)} |\n`;
  }
  return md + '\n';
}

async function main() {
  const apply = process.env.APPLY === '1';
  console.log(`[emdash_purge] scanning DB content for em dashes…${apply ? ' (APPLY mode)' : ''}\n`);
  const flags = await runEmdashPurgeScan();
  const byTable: Record<string, number> = {};
  for (const f of flags) byTable[`${f.table}.${f.column}`] = (byTable[`${f.table}.${f.column}`] ?? 0) + 1;
  for (const [k, v] of Object.entries(byTable)) console.log(`  ${k}: ${v}`);
  const path = join(AUDIT_DIR, 'emdash_purge.out.md');
  writeFileSync(path, renderReport(flags), 'utf8');
  console.log(`\n[emdash_purge] ${flags.length} value(s) flagged. Report: ${path}`);
  if (apply) {
    const n = await applyPurge(flags);
    console.log(`[emdash_purge] APPLY: rewrote ${n} value(s).`);
  }
  process.exit(0);
}

if (isMain(import.meta.url)) {
  main().catch((err) => { console.error(err); process.exit(1); });
}
